import { sortByImportance, extractSourceCitations } from './utils.js';
import {
  cleanDocument,
  isComparisonDocument,
  isProceduralDocument,
} from '../visualizationSuitability.js';

export default function toComparisonViewModel(canonicalIR) {
  const {
    document = {},
    nodes = [],
    comparisons = [],
    relations = [],
    sourceMap = {},
  } = canonicalIR;

  const clean = cleanDocument(document);

  if (!nodes.length) {
    return emptyComparison(clean);
  }

  if (!isComparisonDocument(canonicalIR) || isProceduralDocument(canonicalIR)) {
    return emptyComparison(clean);
  }

  // Priority 1: Canonical comparisons generated by the LLM
  if (comparisons.length > 0) {
    const result = buildComparisonFromCanonical(
      comparisons,
      nodes,
      sourceMap
    );

    if (result.items.length >= 2) {
      return result;
    }
  }

  // Priority 2: Relations
  const comparisonPairs = findComparisonPairs(
    sortByImportance(nodes).slice(0, 10),
    relations
  );

  if (comparisonPairs.length > 0) {
    const result = buildComparisonFromPairs(
      comparisonPairs,
      nodes,
      sourceMap
    );

    if (result.items.length >= 2) {
      return result;
    }
  }

  return emptyComparison(clean);
}

function emptyComparison(clean) {
  return {
    title: clean.title || "Comparison",
    summary: clean.summary || "",
    items: [],
  };
}

function buildComparisonFromCanonical(comparisons, nodes, sourceMap) {
  const nodeMap = Object.fromEntries(nodes.map((n) => [n.id, n]));

  const items = comparisons
    .flatMap((comparison) => comparison.items || [])
    .map((item) => {
      const node = nodeMap[item.itemId];

      return {
        nodeId: item.itemId,
        label: node?.label || item.name || "Item",
        points: (item.criteria || []).map((criterion) => ({
          criterion: criterion.criterion || "Property",
          value: criterion.value || "",
        })),
        sourceRefs: node?.sourceRefs || [],
        citations: node
          ? extractSourceCitations(node, sourceMap)
          : [],
      };
    })
    .filter((item) => item.points.length > 0)
    .slice(0, 10);

  return {
    title: comparisons[0]?.label || "Comparison",
    summary: "",
    items,
  };
}

function findComparisonPairs(nodes, relations = []) {
  const nodeIds = new Set(nodes.map((n) => n.id));

  return relations
    .filter(
      (relation) =>
        relation.relationType === "compared_to" &&
        nodeIds.has(relation.sourceNodeId) &&
        nodeIds.has(relation.targetNodeId)
    )
    .map((relation) => ({
      nodeId1: relation.sourceNodeId,
      nodeId2: relation.targetNodeId,
    }));
}

function buildComparisonFromPairs(pairs, nodes, sourceMap) {
  const nodeMap = Object.fromEntries(nodes.map((n) => [n.id, n]));
  const seen = new Set();

  const items = [];

  for (const pair of pairs.slice(0, 8)) {
    for (const nodeId of [pair.nodeId1, pair.nodeId2]) {
      if (seen.has(nodeId)) continue;

      const node = nodeMap[nodeId];
      if (!node) continue;

      seen.add(nodeId);

      items.push({
        nodeId: node.id,
        label: node.label,
        points: node.summary
          ? [
              {
                criterion: "Description",
                value: node.summary,
              },
            ]
          : [],
        sourceRefs: node.sourceRefs || [],
        citations: extractSourceCitations(node, sourceMap),
      });
    }
  }

  return {
    title: "Comparison",
    summary: "",
    items,
  };
}